language: elixir
elixir:
  - 1.7.3
otp_release:
  - 19.3
addons:
  artifacts:
    debug: true
    paths:
      - $(ls plts/*.plt)
    working_dir: plts
    target_paths:
      - elixir_plts

before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - git clone https://github.com/jeremyjh/dialyxir.git
  - cd dialyxir
  - MIX_ENV=prod mix do deps.get, compile, archive.build
  - MIX_ENV=prod mix archive.install --force
  - cd ..

script:
  - MIX_ENV=test travis_wait 30 mix dialyzer --plt
